ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += sky81296.o
# [5816][FlashLED][akenhsu] Porting LM3644TT Flash LED for ASUS 5816 20150911 BEGIN
obj-$(CONFIG_MSMB_CAMERA) += lm3644tt.o
# [5816][FlashLED]20150911 END
obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o
